### ISSUE TITLE
Asking for a clarification of semantics.

### ISSUE THREAD

**Issue by danielclough** [martindale/genome#2]
I am confused by your statement, "...open-sourcing my genome...while simultaneously retaining complete and exclusive rights."

I generally take "open source" and "exclusive rights" to have contrary meaning. Could you contrast and compare your intention to this [definition of "Open Source"](https://openSource.org/osd).

In what sense do you intend for the source to be open?

**Comment by martindale** [comment]
Open source refers to the visibility of the code itself, but does not confer any rights in either direction.  "Exclusive rights" refers to absolute publisher definition, in that you may not use the code for any purposes without my express permission.
